gormlog: true
app_name: "irisgo"
mysql:
  username: "root"
  password: "HKr33!&"
  addr: "116.31.96.132:3306"
  name: "filclient"
log:
  logger_level: DEBUG #
  logger_file: log
  with_max_age: 7*24h #文件最大保存时间
  with_rotation_count: 5 #设置文件清理前最多保存的个数。
  with_rotation_time: 24h #日志切割时间间隔
addr: ":8080"